# Generated by Django 3.2.13 on 2022-10-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionslistings_bids_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionslistings',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='auctionslistings',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bids',
            name='bidPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.CharField(default='', max_length=300),
        ),
    ]
