# Generated by Django 3.2.13 on 2022-10-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20221019_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionslistings',
            old_name='title',
            new_name='description',
        ),
        migrations.AddField(
            model_name='auctionslistings',
            name='titleList',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='auctionslistings',
            name='url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
