# Generated by Django 3.2.13 on 2022-10-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlists'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchLists',
        ),
        migrations.AddField(
            model_name='auctionslistings',
            name='add_watch_list',
            field=models.BooleanField(default=False),
        ),
    ]
