# Generated by Django 3.2.13 on 2022-10-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20221021_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionslistings',
            name='watch_list',
            field=models.JSONField(default=[]),
        ),
    ]
