# Generated by Django 3.2.13 on 2022-10-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionslistings_watch_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionslistings',
            name='watch_list',
        ),
        migrations.AddField(
            model_name='user',
            name='watch_list',
            field=models.JSONField(default=[]),
        ),
    ]
