# Generated by Django 3.2.13 on 2022-10-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20221021_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watch_list',
            field=models.JSONField(default='[]'),
        ),
    ]
