# Generated by Django 3.2.13 on 2022-10-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watch_list',
            field=models.JSONField(default=[]),
        ),
    ]
