# Generated by Django 3.2.13 on 2022-10-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_user_watch_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid_item_pk',
            field=models.ManyToManyField(related_name='item_bid', to='auctions.AuctionsListings'),
        ),
        migrations.AddField(
            model_name='bids',
            name='bid_user_pk',
            field=models.ManyToManyField(related_name='user_bid', to='auctions.AuctionsListings'),
        ),
    ]
