# Generated by Django 3.2.13 on 2022-10-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_auctionslistings_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionslistings',
            old_name='user',
            new_name='creator',
        ),
    ]
