# Generated by Django 3.2.13 on 2022-10-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_remove_auctionslistings_add_watch_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionslistings',
            name='add_watch_list',
            field=models.BooleanField(default=False),
        ),
    ]
