# Generated by Django 3.2.13 on 2022-10-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionslistings',
            name='catagory',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
