# Generated by Django 3.2.13 on 2022-10-30 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_rename_catagory_auctionslistings_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionslistings',
            name='category',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(default='', max_length=300)),
                ('listing', models.ManyToManyField(blank=True, related_name='category', to='auctions.AuctionsListings')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
