# Generated by Django 3.2.13 on 2022-10-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_auto_20221030_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catagory',
            new_name='category',
        ),
    ]
