# Generated by Django 3.2.13 on 2022-10-30 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0037_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
