# Generated by Django 3.2.13 on 2022-10-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0044_alter_categories_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionslistings',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
