# Generated by Django 3.2.13 on 2022-11-01 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0047_remove_categories_category_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionslistings'),
        ),
    ]
